---
title: "RWorksheet_Sorenio#4a.Rmd"
output: pdf_document
date: "2024-10-14"
---

```{r}
# 1
shoedata <- data.frame(
  ShoeSize = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.0, 9.0, 7.5, 10.5, 8.5, 10.5, 10.5, 8.5, 10.5, 13.0, 11.5, 8.5, 7.0, 6.5, 8.5, 9.0, 8.5, 11.0, 13.0),
  Height = c(66.0, 68.0, 64.5, 65.0, 72.0, 64.0, 71.0, 71.0, 64.0, 74.5, 67.0, 71.0, 77.0, 72.0, 59.0, 72.0, 72.0, 77.0, 66.0, 73.0, 67.0, 67.0, 69.0, 71.0, 70.0),
  Gender = c("F", "F", "F", "F", "F", "M", "M", "M", "F", "F", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M", "M")
)

shoedata
```
# a. Describe the data.
# The data includes shoe size, height, and gender for 25 people. Shoe sizes range from 6.5 to 13, heights from 59 to 77 inches, with 9 females and 16 males. It helps to explore averages and any link between height and shoe size.

# b
```{r}
MALE <- subset(shoedata, Gender == "M")

FEMALE <- subset(shoedata, Gender == "F")

print("Male Data:")

print(MALE)

print("Female Data:")

print(FEMALE)
```
# c
```{r}
MEANSHOE <- mean(shoedata$ShoeSize)

MEANH <- mean(shoedata$Height)

print(paste("Mean Shoe Size:", MEANSHOE))

print(paste("Mean Height:", MEANH))
```
# d
```{r}
relation <- cor(shoedata$ShoeSize, shoedata$Height)

print(paste("Correlation between Shoe Size and Height:", relation))
```
```{r}
# 2
MONTHS <- c(
  "March", "April", "January", "November", "January", "September", "October",
  "September", "November", "August", "January", "November", "November", 
  "February", "May", "August", "July", "December", "August", "August", 
  "September", "November", "February", "April"
)

factor_months_vector <- factor(MONTHS)

print(factor_months_vector)
```

```{r}
# 3
print("Summary of months_vector (character vector):")

summary(MONTHS)

print("Summary of factor_months_vector:")

summary(factor_months_vector)

# The character vector just tells us the total number of months in the data, but it doesn’t show how many times each month appears. On the other hand, the summary of the factor vector is much more useful. It tells us exactly how often each month appears in the data. So, using a factor is better because it helps us see the distribution of the months more clearly, making it easier to analyze.

```

```{r}
# 4

direction_data <- c("East", "West", "North")

frequency_data <- c(1, 4, 3)

new_order_data <- factor(direction_data, levels = c("East", "West", "North"))

print(new_order_data)
```

```{r}
# 5
# a
exceldata <- read.table("import_march.csv", header = TRUE, sep = ",")

View(exceldata)

# b
print(exceldata)

View(exceldata)
```

```{r}
# 6. a
 randsearch <- function() {
  
  rnumber <- readline(prompt="Enter a random number between 1 and 50:")
  if (rnumber < 1 || rnumber > 50) {
    print("The number selected is beyond the range of 1 to 50")
  } else if (rnumber == 20) {
    return("TRUE")
  } else {
    print(paste("The selected number is", rnumber))
  }
}

randsearch()
```

```{r}
# 7. a
minimumbills <- function (price){
  Bills <- c(50, 100, 200, 500, 1000)
  count <- 0
  for (bill in Bills){
    count <- count + price %% bill
    price <- price %% bill
  }
  return(count)
}

sprice <- as.integer(readline(prompt= "Enter the price of the snack: "))
print(paste("Minimum number of bills needed: ", minimumbills(sprice)))
```

```{r}
# 8. a
 Grades <- data.frame( 
   Name = c("Annie", "Thea", "Steve", "Hanna"),
   Grade1 = c(85, 65, 75, 95),
   Grade2 = c(65, 75, 55, 75),
   Grade3 = c(85, 90, 80, 100),
   Grade4 = c(100, 90, 85, 90)
   )

Grades
```

```{r}
# 8. b
for (i in 1:nrow(Grades)) {
  studs <- Grades[i, ]
  average <- (studs$Grade1 + studs$Grade2 + studs$Grade3 + studs$Grade4) / 4
 
  cat(studs$Name, "'s average grade this semester is", average, "\n")
}
```
```{r}
# 8 c

for (j in 2:5) {
  testavg <- sum(Grades[, j]) / nrow(Grades)
  
  if (testavg < 80) {
    cat("The", colnames(Grades)[j], "test was difficult.\n")
  }
}

```

```{r}
# 8 d 

for (i in 1:nrow(Grades)) {
  studs <- Grades[i, ]
  highscore <- studs$Grade1
  
   for (j in 2:5) {
    if (studs[[j]] > highscore)
      highscore <- studs[[j]]
    }
 
 if (highscore > 90) {
    cat(studs$Name, "'s highest grade this semester is", highscore, "\n")
  }
}
```




